"""status column

Revision ID: 406f09d4d862
Revises: fb908c91b697
Create Date: 2021-04-07 19:53:49.673407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '406f09d4d862'
down_revision = 'fb908c91b697'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pvdata', sa.Column('status', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pvdata', 'status')
    # ### end Alembic commands ###
