"""pvdata table

Revision ID: fb908c91b697
Revises: 
Create Date: 2020-03-24 18:52:16.839158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb908c91b697'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pvdata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('dc_1_u', sa.Integer(), nullable=True),
    sa.Column('dc_1_i', sa.Float(), nullable=True),
    sa.Column('ac_1_u', sa.Integer(), nullable=True),
    sa.Column('ac_1_p', sa.Integer(), nullable=True),
    sa.Column('dc_2_u', sa.Integer(), nullable=True),
    sa.Column('dc_2_i', sa.Float(), nullable=True),
    sa.Column('ac_2_u', sa.Integer(), nullable=True),
    sa.Column('ac_2_p', sa.Integer(), nullable=True),
    sa.Column('dc_3_u', sa.Integer(), nullable=True),
    sa.Column('dc_3_i', sa.Float(), nullable=True),
    sa.Column('ac_3_u', sa.Integer(), nullable=True),
    sa.Column('ac_3_p', sa.Integer(), nullable=True),
    sa.Column('current_power', sa.Integer(), nullable=True),
    sa.Column('daily_energy', sa.Float(), nullable=True),
    sa.Column('total_energy', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pvdata')
    # ### end Alembic commands ###
